- app/src/main/res/layout/activity_main.xml
> feat : main ui 추가

- data/src/main/kotlin/com/sooum/data/di/RepositoryModule.kt
- data/src/main/kotlin/com/sooum/data/repository/MeetDetailRepositoryImpl.kt
- data/src/main/kotlin/com/sooum/data/repository/UserRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/MeetDetail.kt
- domain/src/main/kotlin/com/sooum/domain/repository/MeetDetailRepository.kt
- domain/src/main/kotlin/com/sooum/domain/repository/UserRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/GetUserListUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/GetUserUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/meet/GetMeetDetailListUseCase.kt
- gradle/libs.versions.toml
- presentation/build.gradle.kts
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/kotlin/com/sooum/where_android/WhereApp.kt
- presentation/src/main/kotlin/com/sooum/where_android/model/ScreenRoute.kt
- presentation/src/main/kotlin/com/sooum/where_android/theme/Color.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/BottomNavigation.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/MainScreenView.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/friendList/FriendListView.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/friendList/modal/DeleteUserModal.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/friendList/modal/ProfileDetailModal.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/meetDetail/MeetDetailCard.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/meetDetail/MeetDetailView.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/widget/CirecleImageView.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/widget/FavoriteIconButton.kt
- presentation/src/main/kotlin/com/sooum/where_android/ui/widget/UserItemView.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/MeetDetailViewModel.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/UserViewModel.kt
친구목록에서 프로필 클릭시 이동되는 모임활동 화면을 추가하였습니다.
모임활동내 데이터는 임시데이터 입니다.
> feat: 모임활동 화면 추가

- domain/src/main/kotlin/com/sooum/domain/usecase/meet/GetMeetDetailListGroupByYearUseCase.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/kotlin/com/sooum/where_android/ui/main/meetDetail/MeetDetailView.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/MeetDetailViewModel.kt
> fix: 연도가 여러개인 경우 디자인 수정

- presentation/src/main/kotlin/com/sooum/where_android/view/auth/signup/AgreementFragment.kt
> feat: 회원가입 약관동의화면 체크박스 이벤트 구현

- domain/src/main/kotlin/com/sooum/domain/model/PlaceList.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/MyMeetPlaceFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/adapter/AllPlaceListAdapter.kt
- presentation/src/main/res/drawable/shape_background_white.xml
- presentation/src/main/res/drawable/shape_rounded_black_radius_16.xml
- presentation/src/main/res/drawable/toggle_button_selector.xml
- presentation/src/main/res/layout/activity_on_boarding.xml
- presentation/src/main/res/layout/fragment_agreement.xml
- presentation/src/main/res/layout/fragment_email_verification.xml
- presentation/src/main/res/layout/fragment_my_meet_place.xml
- presentation/src/main/res/layout/fragment_on_boarding_first.xml
- presentation/src/main/res/layout/fragment_on_boarding_second.xml
- presentation/src/main/res/layout/fragment_on_boarding_third.xml
- presentation/src/main/res/layout/fragment_password.xml
- presentation/src/main/res/layout/fragment_profile_setting.xml
- presentation/src/main/res/layout/fragment_sign_in.xml
- presentation/src/main/res/layout/fragment_sign_up_complete.xml
- presentation/src/main/res/layout/fragment_social_login.xml
- presentation/src/main/res/layout/item_profile_place_list.xml
- presentation/src/main/res/layout/item_unselected_place.xml
- 모임장소 리스트 추가 
- 모임 정보 수정 기능 추가
> feat: 모임장소리스트 추가 

- presentation/src/main/res/layout/activity_on_boarding.xml
- presentation/src/main/res/layout/fragment_agreement.xml
- presentation/src/main/res/layout/fragment_edit_my_meet_detail.xml
- presentation/src/main/res/layout/fragment_edit_my_meet_memo.xml
- presentation/src/main/res/layout/fragment_edit_my_meet_name.xml
- presentation/src/main/res/layout/fragment_email_verification.xml
- presentation/src/main/res/layout/fragment_my_meet_tab.xml
- presentation/src/main/res/layout/fragment_password.xml
- presentation/src/main/res/layout/fragment_profile_setting.xml
- presentation/src/main/res/layout/fragment_sign_in.xml
- presentation/src/main/res/layout/fragment_sign_up_complete.xml
> design: 이미지 터치 영역 확장

- build.gradle.kts
- gradle/libs.versions.toml
- presentation/build.gradle.kts
- presentation/release/output-metadata.json
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/kotlin/com/sooum/where_android/MyFirebaseMessagingService.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/SocialLoginFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/MainActivity.kt
> feat: fcm 수신 기능 추가

- presentation/src/main/kotlin/com/sooum/where_android/MyFirebaseMessagingService.kt
> fix: null일 경우 알림수신 수정

- presentation/src/main/kotlin/com/sooum/where_android/view/main/MainActivity.kt
> feat: 토큰값 불러오는 함수 제거

- data/src/main/kotlin/com/sooum/data/repository/MeetDetailRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/PlaceDelete.kt
- domain/src/main/kotlin/com/sooum/domain/model/PlaceLike.kt
- domain/src/main/kotlin/com/sooum/domain/model/PlaceStatus.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/AuthActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/MyMeetActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/MyMeetDetailViewModel.kt
> feat: fcm 장소에 대한 데이터 수정하는 기능 추가

- data/src/main/kotlin/com/sooum/data/repository/MeetDetailRepositoryImpl.kt
- presentation/src/main/kotlin/com/sooum/where_android/MyFirebaseMessagingService.kt
> feat: 브로드케스트로 fcm데이터 송신하는 기능 추가

- data/src/main/kotlin/com/sooum/data/repository/MeetDetailRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/Comment.kt
- domain/src/main/kotlin/com/sooum/domain/repository/MeetDetailRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/place/AddCommentUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/place/AddNewPlaceUserCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/place/DeleteCommentUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/place/UpdateCommentUseCase.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/MyMeetDetailViewModel.kt
> feat: fcm 301,302,303에 대한 기능 추가

- data/src/main/kotlin/com/sooum/data/datastore/AppManageDataStore.kt
- data/src/main/kotlin/com/sooum/data/network/auth/AuthApi.kt
- data/src/main/kotlin/com/sooum/data/network/auth/request/LoginRequest.kt
- data/src/main/kotlin/com/sooum/data/repository/AuthRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/LoginResult.kt
- domain/src/main/kotlin/com/sooum/domain/repository/AuthRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/LoginUseCase.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/AuthActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/SignInFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/signup/AuthBaseFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/signup/SignUpCompleteFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/MainActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/AuthViewModel.kt
> feat: 로그인 토큰 저장하는 기능 추가

- data/src/main/kotlin/com/sooum/data/repository/AuthRepositoryImpl.kt
- data/src/main/kotlin/com/sooum/data/repository/MeetDetailRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/InvitedFriend.kt
- domain/src/main/kotlin/com/sooum/domain/repository/MeetDetailRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/meet/fcm/UpdateMeetStatusFromFcmUseCase.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/meetdetail/MyMeetDetailFcmViewModel.kt
- FCM 초대 수락 처리 로직 추가 (모임 ID: 404)
> feat: FCM 초대 수락 처리 로직 추가 (모임 ID: 404)

- data/src/main/kotlin/com/sooum/data/repository/MeetDetailCommentRepositoryImpl.kt
- FCM comment 처리 로직 수정 (ID: 301,302,303)
> feat: FCM comment 처리 로직 수정 (ID: 301,302,303)

- data/src/main/kotlin/com/sooum/data/datastore/AppManageDataStore.kt
- data/src/main/kotlin/com/sooum/data/network/auth/AuthApi.kt
- data/src/main/kotlin/com/sooum/data/network/auth/request/KakaoSignUpRequest.kt
- data/src/main/kotlin/com/sooum/data/repository/AuthRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/KakaoSignUpResult.kt
- domain/src/main/kotlin/com/sooum/domain/repository/AuthRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/KakaoSignUpUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/SocialLoginFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/AuthViewModel.kt
> feat: 카카오 소셜 로그인 회원가입 api 연동

- presentation/src/main/res/layout/activity_on_boarding.xml
> design: 온보딩화면 닷 사이즈 수정

- data/src/main/kotlin/com/sooum/data/network/auth/AuthApi.kt
- data/src/main/kotlin/com/sooum/data/repository/AuthRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/repository/AuthRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/VersionCheckUseCase.kt
- gradle/libs.versions.toml
- presentation/build.gradle.kts
- presentation/src/main/kotlin/com/sooum/where_android/view/splash/SplashActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/SplashViewModel.kt
> refactor: 업데이트 알림 로직 수정

- domain/src/main/kotlin/com/sooum/domain/usecase/auth/VersionCheckUseCase.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/splash/SplashActivity.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/SplashViewModel.kt
> refactor: splashViewModel 버전체크 로직 개선

- data/src/main/kotlin/com/sooum/data/network/auth/AuthApi.kt
- data/src/main/kotlin/com/sooum/data/network/auth/request/EmailVerifyRequest.kt
- data/src/main/kotlin/com/sooum/data/repository/AuthRepositoryImpl.kt
- domain/src/main/kotlin/com/sooum/domain/model/EmailVerifyResult.kt
- domain/src/main/kotlin/com/sooum/domain/repository/AuthRepository.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/EmailVerifyUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/RequestEmailAuthUseCase.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/auth/signup/EmailVerificationFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/AuthViewModel.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/SplashViewModel.kt
- presentation/src/main/res/layout/fragment_email_verification.xml
> feat: 이메일 인증코드 검증기능 구현

- data/src/main/kotlin/com/sooum/data/di/UtilModule.kt
- domain/src/main/kotlin/com/sooum/domain/usecase/auth/DefaultAppVersionProviderUseCase.kt
- domain/src/main/kotlin/com/sooum/domain/util/AppVersionProvider.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/SplashViewModel.kt
- 버전 정보를 UseCase로 분리하고 Hilt DI 적용
> refactor: 버전 정보를 UseCase로 분리하고 Hilt DI 적용

- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/adapter/comment/PlaceCommentListAdapter.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/fragment/MyMeetPlaceDetailFragment.kt
- presentation/src/main/kotlin/com/sooum/where_android/viewmodel/meetdetail/MyMeetDetailCommentViewModel.kt
- presentation/src/main/res/layout/activity_on_boarding.xml
- presentation/src/main/res/layout/fragment_my_meet_place_detail.xml
> feat: 나의 댓글이 목록 상단에 오도록 정렬 기능 추가

- domain/src/main/kotlin/com/sooum/domain/model/ProfileImage.kt
- presentation/build.gradle.kts
- presentation/src/main/kotlin/com/sooum/where_android/util/ProfileDiffUtil.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/adapter/image/ImageListAdapter.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/fragment/MyMeetPlaceDetailFragment.kt
- presentation/src/main/res/drawable/shape_circle_overlay_background.xml
- presentation/src/main/res/layout/fragment_my_meet_place_detail.xml
- presentation/src/main/res/layout/item_profile_image.xml
- presentation/src/main/res/layout/item_profile_image_overflow.xml
> feat: 장소상세화면 프로필 이미지 리스트 적용

- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/adapter/place/OverlapDecoration.kt
- presentation/src/main/kotlin/com/sooum/where_android/view/main/myMeetDetail/fragment/MyMeetPlaceDetailFragment.kt
- 더미데이터 삭제 및 OverlapClass파일 분리
> feat: 더미데이터 삭제 및 OverlapClass파일 분리
